<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Aportaciones.aspx.cs" Inherits="SICAH_Agrupaciones_Aportaciones" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
        <asp:gridview id="GridView1" runat="server" autogeneratecolumns="False" style="z-index: 100;
            left: 6px; position: absolute; top: 20px; width: 556px;" allowsorting="True" 
            autogeneratedeletebutton="True" autogenerateeditbutton="True" 
            onrowediting="GridView1_RowEditing" 
            onrowcancelingedit="GridView1_RowCancelingEdit" 
            onrowupdating="GridView1_RowUpdating" onrowdeleting="GridView1_RowDeleting" 
            backcolor="LightGoldenrodYellow" bordercolor="Tan" cellpadding="2" 
            forecolor="Black" gridlines="None" pagesize="5" BorderWidth="1px">
            <columns>
            
            <asp:templatefield headertext="Inscripción">
                <itemtemplate>
                    <asp:label id="lblid" runat="server" text= <%#Eval("NumInscripcion") %> ></asp:label>
                </itemtemplate>
            </asp:templatefield>
            
            <asp:templatefield headertext="PVYCR">
                <itemtemplate>
                    <asp:label id="lblPVYCR" runat="server" text= <%#Eval("CodigoPVYCR")%> ></asp:label>
                </itemtemplate> 
            </asp:templatefield>
            
            <asp:templatefield headertext="Aportación">
                <itemtemplate>
                    <asp:label id="lblAportacion" runat="server" text= <%#Eval("Aportacion")%> ></asp:label>
                </itemtemplate>
                <edititemtemplate>
                    <asp:textbox id="TXT_Aportacion" runat="server" text=<%#Eval("Aportacion") %>></asp:textbox>
                </edititemtemplate>
            </asp:templatefield>
            
            </columns>
            
            <FooterStyle BackColor="Tan" />
            <PagerStyle BackColor="PaleGoldenrod" ForeColor="DarkSlateBlue" 
                HorizontalAlign="Center" />
            <SelectedRowStyle BackColor="DarkSlateBlue" ForeColor="GhostWhite" />
            <HeaderStyle BackColor="Tan" Font-Bold="True" />
            <AlternatingRowStyle BackColor="PaleGoldenrod" />
            
         </asp:gridview>
    
    
    </div>
    </form>
</body>
</html>
